name: "Main Call"
on:
  push:
    branches:
    - master
jobs:
  call1:
    uses: lyb-rozgaar/test-workflow/.github/workflows/subcall1.yml@main
  call2:
    uses: lyb-rozgaar/test-workflow/.github/workflows/subcall2.yml@main
    
